import java.util.*;

class Student {
    int rollNo;
    String name;

    public Student(int rollNo, String name) {
        this.rollNo = rollNo;
        this.name = name;
    }

    @Override
    public boolean equals(Object o) {  //checking if roll.no is equal for 2 students
        if (o == null || getClass() != o.getClass()) return false;
        Student student = (Student) o;
        return rollNo == student.rollNo;
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(rollNo);  //for every roll.No a unique hashcode is generated by taking rollNo as input
    }

    @Override
    public String toString(){
        return "Student ....{" + "Roll.no =  ....." + rollNo + ", name = '" + name + "}";
    }
}

public class Main {
    public static void main(String[] args) {

//        Set<Integer> set = new HashSet<>();    //O(1) time complexity
//        Set<Integer> set = new LinkedHashSet<>();  //O(n) time complexity

//        Set<Integer> set = new TreeSet<>(); // O(log n) time complexity
//        set.add(10);
//        set.add(20);
//        set.add(30);
//        set.add(5);
//        System.out.println(set);
//
//        set.remove(10);
//        System.out.println(set.contains(10));;
//        System.out.println(set);
//
//        Set<String> setstring = new HashSet<>();
//        setstring.add("Akhila");
//        setstring.add("aNila");
//        setstring.add("Popsicle");
//        setstring.add("Popsicle");
//
//        System.out.println(setstring);

        Set<Student> student = new HashSet<>();

//        student.add(new Student(1,"Akhila"));
//        student.add(new Student(1,"Akhila"));
//        student.add(new Student(2,"Anila"));

        Student s1 = new Student(1,"Akhila");
        Student s2 = new Student(1,"Anila");
        Student s3 = new Student(1,"Akhila");
        Student s4 = new Student(2,"Poggy");

        student.add(s1);
        student.add(s2);
        student.add(s3);
        student.add(s4);

        System.out.println(s1.equals(s2)); //override above , it calls that

        System.out.println(student);

        }
    }
